apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogood
  template:
    metadata:
      labels:
        app: dogood
    spec:
      containers:
        - name: dogood
          image: dogood
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
