apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogood-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogood
  template:
    metadata:
      labels:
        app: dogood
    spec:
      containers:
        - name: dogood
          image: dogood   # Cloud Deploy replaces this
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: dogood-db-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
