apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogood-app
  labels:
    app: dogood
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: dogood

  template:
    metadata:
      labels:
        app: dogood

    spec:
      containers:
        - name: dogood
          image: dogood   # Cloud Deploy replaces this with actual Artifact Registry image

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: dogood-db-secret

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2


            
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: dogood-app
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: dogood
#  template:
#    metadata:
#      labels:
#        app: dogood
#    spec:
#      containers:
#        - name: dogood
#          image: dogood   # Cloud Deploy replaces this
#          ports:
#           - containerPort: 8080
#          envFrom:
#            - secretRef:
#                name: dogood-db-secret
#          resources:
#            requests:
#              cpu: "500m"
#              memory: "512Mi"
