apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogood
  labels:
    app: dogood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogood
  template:
    metadata:
      labels:
        app: dogood
    spec:
      containers:
        - name: dogood
          image: us-central1-docker.pkg.dev/dogood-488720/dogood-repo/dogood:ab3f131
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: dogood-db-secret
