apiVersion: v1
kind: Service
metadata:
  name: dogood-service
spec:
  type: ClusterIP
  selector:
    app: dogood
  ports:
    - port: 80
      targetPort: 8080
      
#apiVersion: v1
#kind: Service
#metadata:
#  name: dogood-service
#spec:
#  type: LoadBalancer
#  selector:
#    app: dogood
#  ports:
#    - port: 80
#      targetPort: 8080
